### ISSUE TITLE
Readme有错别字哦

### ISSUE THREAD

**Issue by ZeroSimple** [Notsfsssf/Pix-EzViewer#12]
- java端通过修改Okhttp的SslSocket实现绕过Sni审查（**既**旁路阻断）直连Pixiv的功能
- java端通过修改Okhttp的SslSocket实现绕过Sni审查（**即**旁路阻断）直连Pixiv的功能

**Comment by Notsfsssf** [comment]
感谢，已修正

**Comment by ZeroSimple** [comment]
> 感谢，已修正

😁
