### ISSUE TITLE
可否考虑增加一个无需会员查看前三十人气作品的功能？

### ISSUE THREAD

**Issue by YuxuanZuo** [Notsfsssf/Pix-EzViewer#13]
官方客户端每次搜索都会有按人气排序的选项，点击后会显示排名前30的预览图，但是如果想详细查看需要开通会员，我通过抓包找到了下面的API，用于获取人气排序的预览图，但同时也包含了所有插画信息:
https://app-api.pixiv.net/v1/search/popular-preview/illust?filter=for_android&include_translated_tag_results=true&merge_plain_keyword_results=true&word={keyword}&search_target=partial_match_for_tags
（使用时需要access token）
请问能否实现这样一个功能？

**Comment by Notsfsssf** [comment]
可以实现，只不过最近比较没时间，欢迎PR:)
