### ISSUE TITLE
识图功能支援不了太大的图

### ISSUE THREAD

**Issue by zombiegun** [Notsfsssf/Pix-EzViewer#15]
好像在16mb以上就不行了

**Comment by Notsfsssf** [comment]
能提供一下使用的图么

**Comment by Notsfsssf** [comment]
目前只能采取bitmap的方法手动压缩图片，但这可能会造成ram资源吃紧，极容易造成崩溃，效果打折，源网站也是直接采取原图上传，识别不成功应该是文件上传过程中网络超时了，没有想到比较好的解决办法
