### ISSUE TITLE
请教大神一个问题

### ISSUE THREAD

**Issue by wangwindlong** [Notsfsssf/Pix-EzViewer#2]
4G直连是怎么实现的，我们项目有个国外服务器也要用到类似的链接方式，方便讲解一下原理么，是用的蓝灯那个库吗

**Comment by Notsfsssf** [comment]
直连并未使用任何第三方服务器来实现，纯粹是本地的，当然，如果你希望让你的应用默认连接到你的vps，可以使用okhttp的proxy

**Comment by wangwindlong** [comment]
给力啊  我试试proxy吧  谢谢啊~
