### ISSUE TITLE
新用户注册的代码为啥注释了

### ISSUE THREAD

**Issue by yuezhengxiaoshi** [Notsfsssf/Pix-EzViewer#26]

**Comment by yuezhengxiaoshi** [comment]
p站不让  还是这边不让..

**Comment by Notsfsssf** [comment]
所以里面有提示“请到官网自行注册”，注册新用户这个功能不打算做，因为限制开关和阅读关闭限制开关的条款还是一样要去官网同意，没有接口，曾经有注册新用户这个功能的时候，很多连P站都不知道的新用户会来找我反馈“为什么看不了XXX"，这极大了增加了我查阅回复反馈邮箱的负担，如果你有兴趣，欢迎PR给应用实现这个功能

**Comment by yuezhengxiaoshi** [comment]
明白了，我刚接触android，正在学习，感谢开源。

**Comment by tekoki** [comment]
请问你是？我好像忘记是什么时候注册了，不好意思


------------------&nbsp;Original&nbsp;------------------
