### ISSUE TITLE
识图功能可以再优化一下

### ISSUE THREAD

**Issue by xushet** [Notsfsssf/Pix-EzViewer#3]
1比如识图完成一次后，再次点击识图界面的放大镜图标时，默认显示上次使用的文件夹，2支持其他应用通过分享功能菜单调用识图功能，3显示最近识图的记录并保留id链接可点击方便再次查看，希望PxEz越来越好，谢谢

**Comment by Notsfsssf** [comment]
感谢建议，第3点与历史记录功能重叠，第2点已经在新发布的版本实现了，请更新到最新版。
