### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [Notsfsssf/Pix-EzViewer#33]
请问是否可以将应用提交到 F-Droid ？

**Comment by Notsfsssf** [comment]
F-Droid以国内的环境来看下载速度并不理想，国外有google play，感觉没什么必要

**Comment by linsui** [comment]
F-Droid 主要是面向不使用 Google Play ，以及注重隐私开源的用户的。从使用角度本应用内置更新机制所以不会有区别。如果感到比较麻烦没有必要，关闭此 issue 即可。谢谢 :smile:
