### ISSUE TITLE
保存图片cache未清理导致缓存暴涨

### ISSUE THREAD

**Issue by ultranity** [Notsfsssf/Pix-EzViewer#34]
设备:米6，系统Android O

保存图片后下载缓存未如期删除，导致缓存暴涨，没机会立马debug,先提个issue在这儿

`ImgDownLoadWorker. kt` 内有相关内容
```
cacheFile.inputStream().copyTo(file.outputStream())

cacheFile.deleteOnExit()
```
但删除步骤似乎并没有被触发。

要不要考虑跳过缓存-复制这一步直接下载到指定文件夹？（虽然提出来就觉得有点问题，现有下载队列稳妥起见用缓存也合理）

**Comment by Notsfsssf** [comment]
感谢反馈，我似乎误解了deleteOnExit()的用法，`Deletion will be attempted only for normal termination of the
     * virtual machine, as defined by the Java Language Specification.`，然而这需要android的整个vm退出，已经替换为delete，将在下一次更新:)
