### ISSUE TITLE
这个绕过旁路阻断的方法可用于浏览器吗

### ISSUE THREAD

**Issue by 850710247liu** [Notsfsssf/Pix-EzViewer#39]
用来访问世界上(除暗网)的任何网站？

**Comment by 850710247liu** [comment]
或者还有其他软件用了这个方法？？？

**Comment by Notsfsssf** [comment]
软件无关

**Comment by yogaskung** [comment]
只有沒有IP封鎖的網站可以，比如pixiv用了Yahoo的CDN，官方網只能看servername來封鎖
參見https://github.com/goproxy0/goproxy/issues/7#issuecomment-333748672
