### ISSUE TITLE
关于图片的问题

### ISSUE THREAD

**Issue by 850710247liu** [Notsfsssf/Pix-EzViewer#40]
搜索下面每个热门标签背后的图片都很不错，是否可以增加一个长按到p站图片详细页的功能
还有pixivition里的好图片现在不能保存，也不能跳转到p站图片详细页

**Comment by Notsfsssf** [comment]
功能建议描述并不是很清晰...版本号能提供一下么，我这边测试跳转是没有问题的

**Comment by 850710247liu** [comment]
我的意思是说这些标签背后的图片

**Comment by 850710247liu** [comment]
我的意思是标签背后的图片，如图https://sm.ms/image/feiZvTIYOPjLCJF（图床）

**Comment by 850710247liu** [comment]
我的意思是标签背后的图片，如图
图床

https://sm.ms/image/feiZvTIYOPjLCJF

**Comment by 850710247liu** [comment]
标签背后的图片保存

**Comment by Notsfsssf** [comment]
了解了，我会在后面的版本添加这个功能

**Comment by 850710247liu** [comment]
还有在pixivsion里面显示的图片现在是无法保存的，希望后续能加上这个功能 ...(｡•ˇ‸ˇ•｡) ...

**Comment by wzf-an** [comment]
以图搜图用不了了

**Comment by Notsfsssf** [comment]
已发布
