### ISSUE TITLE
希望查看原图时再次点击屏幕能关闭

### ISSUE THREAD

**Issue by philosopher233** [Notsfsssf/Pix-EzViewer#41]
我的手机用的是虚拟按键, 查看原图时会自动收回去, 想关闭时要先上划调出虚拟按键, 比较不方便, 希望点一下屏幕就能关闭。

**Comment by Notsfsssf** [comment]
嗯，收到

**Comment by philosopher233** [comment]
感谢!
再考虑一下退出时自动清理缓存? 只能从普通用户的角度来提建议, 抱歉了!
