### ISSUE TITLE
希望能控制桌面小工具所显示的图片类型

### ISSUE THREAD

**Issue by wzxyisme** [Notsfsssf/Pix-EzViewer#45]
希望能控制桌面小工具所显示的图片类型
![Screenshot_2020-02-25-00-21-33-729_com miui home](https://user-images.githubusercontent.com/45878990/75170442-14c52800-5765-11ea-9b6b-4c0c4e5ac69c.jpg)
我个男的不是很喜欢BL╮( •́ω•̀ )╭

**Comment by Notsfsssf** [comment]
如果希望控制图片类型的话，会涉及到登录后的token刷新问题，我不希望在后台加个定时刷新服务，目前用的是无需token的登录界面滚动播放的图片的接口
