### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by Henry-ZHR** [Notsfsssf/Pix-EzViewer#49]
插画标题含有字符`/`时保存成功/失败的Toast不会显示该字符。

例如插画标题为`2020/03/09`，则显示的消息是`20200309保存成功`。

可能`\`也会发生同样问题。

**Comment by Notsfsssf** [comment]
因为title默认做了路径处理，所以会去掉非法字符，最近没什么时间更新，我找个时间换成Downloadmanger吧

**Comment by Notsfsssf** [comment]
已解决
