### ISSUE TITLE
tab操作逻辑优化

### ISSUE THREAD

**Issue by xushet** [Notsfsssf/Pix-EzViewer#50]
画师界面往右滑应该换到下一个tab了不然按钮太高不好点[<a href="https://sm.ms/image/5ZNoMLcF4KGEaYJ" target="_blank"><img src="https://i.loli.net/2020/03/15/5ZNoMLcF4KGEaYJ.png" ></a>](url)

**Comment by Notsfsssf** [comment]
这个月没有太多空余时间，等我有时间了调整一下ui吧

**Comment by ygsk10** [comment]
> 这个月没有太多空余时间，等我有时间了调整一下ui吧
![Screenshot_20200317-063627](https://user-images.githubusercontent.com/60314251/76829072-3d978500-681a-11ea-86b0-cee522e59a5e.jpg)
“下载”靠边距离在gesture navigation下会与“返回”操作混淆，建议调整到和“分享”相同的距离（截图右上可以看出距离不同）
#ui优化
