### ISSUE TITLE
关于pixiv登录的实现

### ISSUE THREAD

**Issue by Helo-Man** [Notsfsssf/Pix-EzViewer#56]
我也想自己写一个pixiv的应用，把自己收藏夹里面一些质量不够高的作品筛选出来，但是目前关于登录方面遇到了reCAPTCHA的问题，因此想请教一下你们是如何解决这个模拟登录的问题的，是有什么第三方的登录方法吗？

**Comment by Notsfsssf** [comment]
reCAPTCHA是网页登录才会出现的，应用使用的是应用的登录接口，如果只希望使用网页接口，可以参考[Starx_Pixiv_Collector](https://github.com/SuzukiHonoka/Starx_Pixiv_Collector)的解决办法,由 [SuzukiHonoka](https://github.com/SuzukiHonoka)编写，非常完善

**Comment by Helo-Man** [comment]
哦哦好的谢谢

**Comment by Helo-Man** [comment]
额外问一个问题，你们有pixiv应用接口或者pixiv官方有应用接口的文档吗？因为这边我主要还是一个学习阶段，对应用接口的理解可能是和开发telegram-bot一样的交互形式。不知道我的理解有没有问题？

**Comment by Notsfsssf** [comment]
并没有文档，项目的接口都是自己调试出来的，不过你可以参考 [pixivpy](https://github.com/upbit/pixivpy)项目，给的比较详细

**Comment by Helo-Man** [comment]
哦哦好的
