### ISSUE TITLE
asking for pix.ezviewer removed from play store?

### ISSUE THREAD

**Issue by conchetumare123** [Notsfsssf/Pix-EzViewer#57]
hello im here only for this ask because i love pix-ez and and because I couldn't continue using it because they removed it from the play store. I would like to know if there is another way to use it? im noob so...

**Comment by Notsfsssf** [comment]
Hi,You can go to the [release](https://github.com/Notsfsssf/Pix-EzViewer/releases) page to get the installation package, but this installation package is a universal version of China, integrated bugly automatic update service (provided to users who do not install gms)
I am looking for google play customer service to appeal. If there is still no way, I will use the new package name and rewrite the application to resubmit.

**Comment by conchetumare123** [comment]
thank you so much, i love you ;)

**Comment by conchetumare123** [comment]
me sirvio, muchas gracias por contestarme.

**Comment by conchetumare123** [comment]
It helped me, thank you very much for answering me.

**Comment by Notsfsssf** [comment]
You're welcome
