### ISSUE TITLE
照片识别功能无法使用

### ISSUE THREAD

**Issue by HeNrY7107** [Notsfsssf/Pix-EzViewer#58]
在更新到最新版本前还能的，现在就算卸载了重新下载回旧版也不能了。
选择照片识别是出了这个错误
![Screenshot_2020-04-09-16-23-01-987_com perol asdpl play pixivez](https://user-images.githubusercontent.com/36949626/78874089-68be6e80-7a7e-11ea-8b22-99097ca1082b.jpg)
写着：
服务器或本地发生错误SSL handshake timed out

能修吗？

**Comment by Notsfsssf** [comment]
你可以用浏览器尝试访问https://saucenao.com/  
如果无法打开，说明当前网络环境访问不到saucenao，这我也没办法
如果能够打开，尝试把应用也加入到与浏览器同一环境
