### ISSUE TITLE
登录时崩溃

### ISSUE THREAD

**Issue by Not-too** [Notsfsssf/Pix-EzViewer#6]
应用在登录时发生崩溃，之后每次打开应用也都会崩溃
log如下(应该没错)
[https://pan.baidu.com/s/1714uXuUtnyGsd7UVQKbLwQ](url) 
系统5.1
  （上不了p站真难受）

**Comment by Notsfsssf** [comment]
尝试过能够正常登陆，图示错误并不是APP造成的，没有详细的崩溃日志吗

**Comment by Not-too** [comment]
重新录了一遍log，应该行了……吧？

**Comment by Notsfsssf** [comment]
@Not-too 把log发反馈邮件，如果对github不是很熟悉的话，这也是我建议的反馈方式。我并没有看到你重录的log

**Comment by Not-too** [comment]
非常抱歉，这是我第1次反馈。另外log就在那个百度网盘的链接里

**Comment by Notsfsssf** [comment]
log已收到，会很快进行修复的

**Comment by Notsfsssf** [comment]
方便留个邮箱帮助我进行测试么

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Not-too <notifications@github.com>
发送时间: Monday, July 22, 2019 10:55:02 PM
收件人: Notsfsssf/Pix-EzViewer <Pix-EzViewer@noreply.github.com>
抄送: Perol_Notsfsssf <asdplk3@live.com>; Comment <comment@noreply.github.com>
主题: Re: [Notsfsssf/Pix-EzViewer] 登录时崩溃 (#6)


非常抱歉，这是我第1次反馈。另外log就在那个百度网盘的链接里

―

**Comment by Not-too** [comment]
发到酷安私信里了
