### ISSUE TITLE
昨天更新后，打开程序秒闪退

### ISSUE THREAD

**Issue by wialny** [Notsfsssf/Pix-EzViewer#8]
mate20p安卓9，更新1.3.1R前正常

**Comment by Notsfsssf** [comment]
@wialny 提供一下错误日志，清除缓存然后重试

**Comment by wialny** [comment]
清除数据后好了😓


请问错误日志在哪找？
应该就是上一两个版本开始使用的，从googleplay下载和更新

**Comment by Notsfsssf** [comment]
华为要导出错误日志比较麻烦，还是等待google play收集的上报信息吧，下版本我会加入错误信息详细反馈的提示以及强制让用户读完用前必读

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: wialny <notifications@github.com>
发送时间: Tuesday, July 30, 2019 12:29:32 PM
收件人: Notsfsssf/Pix-EzViewer <Pix-EzViewer@noreply.github.com>
抄送: Perol_Notsfsssf <asdplk3@live.com>; Comment <comment@noreply.github.com>
主题: Re: [Notsfsssf/Pix-EzViewer] 昨天更新后，打开程序秒闪退 (#8)


清除数据后好了😓

请问错误日志在哪找？
应该就是上一两个版本开始使用的，从googleplay下载和更新

**Comment by wialny** [comment]
好的, 感谢解答.
