### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by WWSBB1** [Notsfsssf/Pix-EzViewer#81]
开启嗅探的时候显示证书不信任,然后网页无法加载,不开启嗅探后在登录账号时,点击登录后自动刷新又跳回登录界面,没有登录上

**Comment by Notsfsssf** [comment]
打开不要绕过sni，用代理，用chrome登录
不要用edge或者国产浏览器，因为他们默认会拦截这个[PKCE](https://oauth.net/2/pkce/)协议，除非你明白怎么设置协议跳转
登录成功后会唤起app进行auth token验证的

**Comment by WWSBB1** [comment]
解决了，发现是因为我安装着pixiv的问题，我不了解具体原因，不过同时安装着pixiv好像会影响到登录。
